### ISSUE TITLE
Canadian census tracts should be default "boundary id"

### ISSUE THREAD

**Issue by michellemho** [CartoDB/bigmetadata#122]
@talos @nygeog 

### Context
Danny was demoing Data Observatory to a potential customer in Vancouver. He wanted to add "% of owner households with a mortgage" to point data using Builder Analysis.

### Current Result
He noticed that the measures were being pulled from "census subdivisions", which is not the smallest boundary level.

### Expected result
We expected results to be pulled from the smallest boundary level for point data. We were also wondering what was happening "behind the scenes" with the observatory SQL analysis functions, and in which Github repo we could track this down (Camshaft? Observatory extension?)

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version* 
Chrome

### .carto file
*Don't forget to rename .carto file to .zip file to be able to upload to github*

[Canada_DO_Test_Geog+(on+2016-12-22+at+21.36.38).carto.zip](https://github.com/CartoDB/bigmetadata/files/669919/Canada_DO_Test_Geog.on.2016-12-22.at.21.36.38.carto.zip)

**Comment by talos** [comment]
Investigating.

**Comment by talos** [comment]
The problem here is that Canadian census tracts are relatively sparse, and in smaller towns like this our algorithm to choose the best geometry doesn't perform particularly well.  I see two possible resolutions:

1. The interface exposes a slider to choose resolution (this is in mockups).
2. We experiment with using smaller tiles in the raster summary, as they can better capture details like this.

@nygeog What is the urgency of taking care of this?

**Comment by nygeog** [comment]
Not too urgent.

**Comment by javitonino** [comment]
This is fixed by a combination of fixes to raster generation as well as adding the slider to be able to choose in the UI. This should be already available to team, and soon-ish to everyone.
