### ISSUE TITLE
Fix OBSMetaToLocal bug

### ISSUE THREAD

**Issue by michellemho** [CartoDB/bigmetadata#125]
Running `make -- run carto OBSMetaToLocal` in brand new bigmetadata environment fails because there the relation "observatory.obs_meta" does not exist yet.

**Comment by talos** [comment]
We should be able to resolve this by using `IF EXISTS` as part of the `ALTER TABLE` statement.

* [Postgres docs](https://www.postgresql.org/docs/9.5/static/sql-altertable.html)
* [Location of problematic lines](https://github.com/CartoDB/bigmetadata/blob/master/tasks/carto.py#L1121) (there are two alter table statements that don't include `IF EXISTS`).

Kicking it back to @michellemho because this should be an easy fix. :)

**Comment by talos** [comment]
Taking this over, as the code fix is going to be a bit more work.
