### ISSUE TITLE
Null Values for Census Tracts

### ISSUE THREAD

**Issue by MichaelSpichiger** [CartoDB/bigmetadata#222]
When I try to use the enrich from data observatory analysis, and try to add population the entire column returns null. I'm not sure if I'm not using the right boundaries or not. The data imports fine using SQL code so there already exists a population column that I want.

**Comment by MichaelSpichiger** [comment]
[Geomarketing w_ Clusters (on 2017-07-24 at 13.40.30).zip](https://github.com/CartoDB/bigmetadata/files/1169966/Geomarketing.w_.Clusters.on.2017-07-24.at.13.40.30.zip)

**Comment by michellemho** [comment]
I replicated Michael's analysis, and found the same errors. Null values are returned when trying to use the new DO Analysis UI to augment US Census Tracts with Total Population from 2011 - 2015 with normalization by square kilometre and without normalization. I also tried to augment with the US State population, and got null results as well.

**Comment by javitonino** [comment]
So, this dataset has some invalid geometries:
```sql
SELECT COUNT(*) FROM nyed WHERE NOT ST_IsValid(the_geom)
39
```

An easy fix for now, is to filter the original dataset with `WHERE ST_IsValid(the_geom)` and then run the analysis.

Regarding DO, the problem here is that, given that we pass all geometries in a single array, if a single geometry is incorrect, the whole analysis will fail, even though we have data for all the other points. We should improve this, we can use this ticket to track it.

**Comment by juanignaciosl** [comment]
We're working on this with a pre check: CartoDB/cartodb-management/issues/4965

**Comment by ethervoid** [comment]
Deployed the precheck, this issue should be fixed
