### ISSUE TITLE
Cached analysis won't run again

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#225]
When you run an analysis and the results are cached, querying for the same measurement won't resolve. It seems to work on a new analysis node.

**Comment by ethervoid** [comment]
This is working as intended. Is how the analysis API works. 

The DO analysis, among others, is a cached analysis which means that the result is stored in a table called `analysis_{{hash}}` and when the same analysis (a DO analysis with the same input data and parameters) is requested, the analysis uses the cache data.

It works this way to avoid users doing the same analysis every time the map is loaded and saving them credits for the same results.

I can't think a reason the let the user execute the same analysis again, have in mind that if the input table changes with for example new rows, deletions or updates the analysis is going to be executed again because the cache is invalidated.

What do you think?

**Comment by noguerol** [comment]
Of course it should be cached, the problem is that the analysis gets stuck retrieving the cached table.

**Comment by ethervoid** [comment]
Ah ok, I didn't understand that from the description of the issue. Sorry

**Comment by javitonino** [comment]
*STR*
1. Create a DO analysis and run it
2. Edit the analysis, choose a different measure and run it
3. Edit the analysis again and choose the first measure, run it.

The Apply button gets stuck in a spinner.

**Comment by xavijam** [comment]
So, after a bit of research with @nobuti, looks like that the map instantiation already sends that the analysis is ready, and UI (in this case the apply button) didn't expect that. In fact, we have checked and the column generated in any case is correct. So, those two things:

- The apply button changes the state correctly (it changes to disable), but it doesn't remove the spinner.
- We don't display the notification about it has finished (but it did).
