### ISSUE TITLE
Analysis with polygons that was working with old DO UI don't work with the new DO UI

### ISSUE THREAD

**Issue by noguerol** [CartoDB/bigmetadata#232]
Copy from https://github.com/CartoDB/cartodb-management/issues/4962 so we can maintain the milestone.

**Comment by juanignaciosl** [comment]
@noguerol do you have STR? We think that this has already been addressed. cc @ethervoid @javitonino

**Comment by noguerol** [comment]
As per the original ticket: augmenting polygons with US Total Population/Asian population.

**Comment by javitonino** [comment]
Here's a map, following the STR. The augmentation works fine, returning values for both population columns, in rural and urban areas.

[Untitled map 1 (on 2017-08-08 at 08.14.29).carto.zip](https://github.com/CartoDB/bigmetadata/files/1207301/Untitled.map.1.on.2017-08-08.at.08.14.29.carto.zip)

So it looks like this has been fixed by some of the changes we did recently. @noguerol Can you provide an STR, or even better, a `.carto` that still reproduces this issue? Otherwise, we'll close it as resolved.

**Comment by noguerol** [comment]
Nope, so closing.
