### ISSUE TITLE
make us-huc fails

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#279]
Review the US HUC data import

**Comment by antoniocarlon** [comment]
Downloading the "NHD Plus V2 Watershed Boundary Dataset" from the EPA FTP (`ftp://newftp.epa.gov/epadatacommons/ORD/EnviroAtlas/NHDPlusV2_WBDSnapshot_EnviroAtlas_CONUS.gdb.zip`) gives an error (`ERR_CONNECTION_RESET` or `ERR_CONNECTION_TIMED_OUT`).

I have already [contacted EPA ](https://www.epa.gov/enviroatlas/forms/contact-us-about-enviroatlas) asking them to fix the download.

**Note:** The Enviroatlas Data Download catalog web site is https://www.epa.gov/enviroatlas/enviroatlas-data-download-step-2

**Comment by javitonino** [comment]
Hey, I took a quick look at this because it reminded me of something. Basically, this is a problem with the fact that FTP uses two connections (control/data) and the control connection times out, so wget hangs when closing the connection. Using `curl` fixes this, as it sets the proper keepalives.

Sending a PR...
