### ISSUE TITLE
us.census.tiger fails

### ISSUE THREAD

**Issue by antoniocarlon** [CartoDB/bigmetadata#299]
The target `make us-tiger` fails:

    File "/bigmetadata/tasks/us/census/tiger.py", line 302, in columns
      clipped[colname + '_clipped']._column: GEOM_NAME

Example: task `SplitSumLevel(year=2015, geography=county)`

**Comment by antoniocarlon** [comment]
Executing the tiger task in parallel throws `Can't attach instance XXX another instance with key YYY is already present in this session`. This may be related to parallel execution (two workers executing the same `ColumnsTask` at the same time on the same session)

**Comment by ethervoid** [comment]
We've been dealing with an issue with the `ShorelieClip` task because is producing an [OOM](https://www.kernel.org/doc/gorman/html/understand/understand016.html) even adding more RAM to the ETL machine. 

Now is time to check how we can improve the memory footprint of that task in order to be able to execute it :\

**Comment by javitonino** [comment]
We are still not sure about OOM problems, but they seem to be temporal. Running the tasks in isolation typically works. We had the same problems in the old machines.

As this is a seldom run task, we can survive with the current state of affairs, but we'll keep an eye out to try to identify the problem.

**Comment by javitonino** [comment]
Reopening this to track some possible solutions to OOM.
