### ISSUE TITLE
Spanish proper names values are returned with a bad format

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/bigmetadata#309]
* Spanish proper names values are returned with a bad format. I have tried with municipalities, but I suppose it will also happen with provinces. This is my query:

```sql
WITH data AS (
  SELECT cartodb_id as id, ST_PointOnSurface(the_geom) as the_geom FROM madrid_cdp
),
meta AS (
  SELECT OBS_GetMeta(ST_SetSRID(ST_Extent(the_geom), 4326),
  '[{"numer_id": "es.cnig.name_muni"}]'
  , 1, 1) meta
FROM data),
b as (
SELECT id, (data->0->>'value')::Text as val
FROM OBS_GetData(
       (SELECT ARRAY_AGG((the_geom, id)::geomval) FROM data),
       (SELECT meta FROM meta)))
UPDATE madrid_cdp a SET municipality = b.val FROM b WHERE a.cartodb_id = b.id
```

* This is the dataset: [madrid_cdp.zip](https://github.com/CartoDB/bigmetadata/files/1284713/madrid_cdp.zip)

* Result:

![thumbnail 003](https://user-images.githubusercontent.com/5215798/30164568-406bc49e-93dd-11e7-9ba1-04dbf2d074fe.png)

**Comment by antoniocarlon** [comment]
The problem seems to be in the Shapefile encoding. The `DBF` file within the Shapefile is supposed to be encoded (for historical reasons) using `ISO-8859-1` but in some cases is encoded using `UTF-8` (or other encodings).

We can try to fix this using the `-lco ENCODING=UTF-8` parameter when calling `ogr2ogr` but we need to know what is the encoding of the data source. One possible approach could be converting the data to `CSV` (also using `ogr2ogr`) and get the encoding using the `file` command.

**Comment by javitonino** [comment]
Solved with the same changes that other countries.
