### ISSUE TITLE
Add 2016 Canada Census data

### ISSUE THREAD

**Issue by terrett101** [CartoDB/bigmetadata#324]
A customer (Economical Insurance) made me aware that Canada has completed a census as recently as 2016 and is currently in the process of releasing the data (schedule [here](http://www12.statcan.gc.ca/census-recensement/2016/ref/release-dates-diffusion-eng.cfm)).

The DO currently contains the 2011 Canadian census. Can we begin to bring in the latest 2016 data?

**Comment by juanignaciosl** [comment]
cc @hannahblue @kevin-reilly

**Comment by juanignaciosl** [comment]
@hannahblue you moved this to "Ready for Development". Should we begin? Nobody gets notified when an issue is moved from one column to another, so please mention me when we should.

**Comment by hannahblue** [comment]
Thanks for asking, @juanignaciosl. I moved it there because it's ready for development whenever there's time for it. However, right now it's not prioritized above what the team is already working on. 

We'll probably end up with a good amount of items in this list waiting to be prioritized for dev. I'll change the name to something more clear.

**Comment by juanignaciosl** [comment]
Ok, thanks!

**Comment by hannahblue** [comment]
@juanignaciosl this is ready to begin whenever you guys can get started on it. Thanks

**Comment by antoniocarlon** [comment]
**Note:** don't forget to add the new Canada Dissemination Areas (https://github.com/CartoDB/bigmetadata/issues/377)
