### ISSUE TITLE
Provide a CSV with needed measurements to Geographica

### ISSUE THREAD

**Issue by juanignaciosl** [CartoDB/bigmetadata#508]
[Measurements](https://docs.google.com/spreadsheets/d/1EsH0vWR59pdhOnwxflx4BK-GN1n-Z5s6dD_s8rHXYCQ/edit?usp=sharing).

**Comment by ethervoid** [comment]
### Current status

I have a new task in our ETL that generates the CSV using a JSON where you define the measurements to be extracted.

- [x] State
- [x] County
- [x] Census tract
- [x] Block group
- [ ] Block

##### Issues

- Cant generate block level because we need the interpolation between block_group and block due to the lack of data from ACS for the block level
- Cant include Zillow data because is only available for Zip code. We could add it for State and County (#510)
- Spielman singleton data is only for census tract. Maybe we could interpolate block_group and block levels with the census tract one (#511)
