### ISSUE TITLE
User Friendly Column Names for MC data in Premium Data Library

### ISSUE THREAD

**Issue by hannahblue** [CartoDB/bigmetadata#540]
We need to change the column names when we share MC data in the PDL to something more descriptive. @alissarose we may need to have you advise us on column names.

Also, can we please change the data types of any scores that are saved as strings to number? 

@juanignaciosl

**Comment by juanignaciosl** [comment]
# Types

Type is based on the automatic detection on file import. Most of the scores are numbers. Nevertheless, I've there are some strings, probably because of a high number of nulls. This can be fixed manually in the PDL table. I've changed all of them: total_merchants_ep total_merchants_app ticket_size_country_score_ep ticket_size_country_score_app ticket_size_metro_score_ep ticket_size_metro_score_app ticket_size_state_score_ep ticket_size_state_score_app growth_metro_score_ep growth_metro_score_app growth_state_score_ep growth_state_score_app stability_country_score_ep stability_country_score_app stability_metro_score_ep stability_metro_score_app stability_state_score_ep stability_state_score_app transactions_country_score_ep transactions_country_score_app transactions_metro_score_ep transactions_metro_score_app transactions_state_score_ep transactions_state_score_app sales_country_score_ep sales_country_score_app sales_metro_score_ep sales_metro_score_app sales_state_score_ep sales_state_score_app.

```sql
update cincinnati_block_groups_mrli_012012_04_2018 set COLUMN = null where COLUMN = '';
alter table cincinnati_block_groups_mrli_012012_04_2018 alter COLUMN type integer using COLUMN::integer;
```

# Naming

- The export is done in SHP format, which has a 10 characters limit for column names. For example, `total_merchants_ep` gets translated to `total_me_1`.  I'll do some tests replacing SHP with GPKG, and I'll change the type of the columns. Naming is likely to be descriptive enough. Stay tuned.

**Comment by juanignaciosl** [comment]
I've reloaded it into your accounts, you should be able to connect the dataset again and you'll get numbers instead of strings for scores and meaningful names. If you had already imported it, your imported dataset will still be there but disconnected from Data Library (it will be a normal dataset, not a synced one).

**Comment by hannahblue** [comment]
Thanks @juanignaciosl!!

Just tried it out and got this error:

![screen shot 2018-08-03 at 8 58 34 am](https://user-images.githubusercontent.com/7182102/43644116-959934fc-96fb-11e8-97c3-b246b6d253a6.png)

**Comment by alissarose** [comment]
happy to help with naming if needed but reads like @juanignaciosl has got it covered 💪 
but ping/tag/tell me what you need and i'm there

**Comment by juanignaciosl** [comment]
@hannahblue f*ck. I'll report it to support/RT. That happened to me once. When I was trying to reproduce the error, I retried and worked. Underneath, there's a ogr2ogr error. My current bet is that there are different ogr2ogr versions in different queue servers. Please retry a few times and let me know if it works.

**Comment by hannahblue** [comment]
Ah ok. Thanks for reporting to support/RT. I just tried again and still got the error.

**Comment by juanignaciosl** [comment]
Issue: CartoDB/support/issues/1688

It eventually works, we're not sure if it's related to retrying or just waiting. Keep an eye on that issue.
