### ISSUE TITLE
Analyse possible bug in Data Observatory Sociodemographic data

### ISSUE THREAD

**Issue by hannahblue** [CartoDB/bigmetadata#563]
From @xavipereztr:

Hi,

As Margara reported in: https://github.com/CartoDB/CARTO-Geographica-Services/issues/38 

_@xavipereztr expressed some concerns regarding the sociodemographic statistic shown in the application, in particular that in many areas the dominant profile is either "Males <=24" or "Females >=65". We have double-checked these stats by comparing the results we provide vs the results we get by querying the Data Observatory API directly and everything seems to be correct. By doing this we've also gladly discovered that the approximations we do by doing the aggregations for the isochrones' geometries using the underlying grid cells are actually quite accurate (3-6% of error)._

When you check the socio-demographic data aggregated in Reveal's isolines around a store, the VAST majority (if not all) predominant profiles are either "Males <24 years" or "Females >65 years"...I find this very hard to believe, even after checking some sociodemos stats from the census.

![screen shot 2018-08-24 at 13 05 25](https://user-images.githubusercontent.com/29253053/44582951-97051280-a7a3-11e8-9cf5-06463dbc9eab.png)

![screen shot 2018-08-24 at 13 05 34](https://user-images.githubusercontent.com/29253053/44582952-97051280-a7a3-11e8-88cf-fd35a938cb2e.png)

![screen shot 2018-08-24 at 13 05 49](https://user-images.githubusercontent.com/29253053/44582953-979da900-a7a3-11e8-89c9-00ffa931e376.png)

![screen shot 2018-08-24 at 13 06 24](https://user-images.githubusercontent.com/29253053/44582956-979da900-a7a3-11e8-8ce0-33222a6d8387.png)

![screen shot 2018-08-24 at 13 07 25](https://user-images.githubusercontent.com/29253053/44582957-979da900-a7a3-11e8-9f70-194d0f0d1a33.png)

![screen shot 2018-08-24 at 13 08 40](https://user-images.githubusercontent.com/29253053/44582958-98363f80-a7a3-11e8-8ca7-1ecb3268a41c.png)

Geographica has:

* Identify an isochrone in which the predominant sociodemographic profile is Male <= 24, and another in which the predominant profile is Female> = 65
* Save service response / isochrones / data for identified isochrones
* Obtain the geometries of said isochrones in the table of isolines
* Make a query to the API of the DO with the geometries of the previous step
* Check that the data returned by the API matches the data returned by the service / isocrones / data

So...can it be an issue from within the DO and how the data is computed and served there?

@juanignaciosl, @antoniocarlon, @ethervoid

**Comment by juanignaciosl** [comment]
cc @CartoDB/rt-managers

**Comment by ethervoid** [comment]
What are the SQL query are you using to get the data? What queries to DO are you doing?

**Comment by ethervoid** [comment]
I've been doing some research on the INE data we use for the Spanish demographics using my hometown where I know how the demographic works.

Using two known postal codes from Valladolid I've checked two things:

### The population data is right

I checked if the sum of all the demographic data for a female and male population is equal to 1 (for the normalized data). For the two targeted postal codes, we get 100% or 1 as you can see below

```
In [43]: sum(code_47010)
Out[43]: 1.0000000000000007
In [47]: sum(cod_47610)
Out[47]: 1.0000000000000004
```

### Sum of all the defined ranges

I've taken all the [defined ranges](https://github.com/CartoDB/Reveal-api/blob/master/db/do_es.sql#L46-L53) and made the sum of the data to check if the result agrees with my knowledge of the neighborhood

```
47010 (old people neighborhood)

m_0_24_male : 2299.804399181663
m_0_24_female : 2216.767102177204
m_25_34_male : 1378.144900788533
m_25_34_female : 1278.095286326365
m_35_44_male : 1847.760446405718
m_35_44_female : 1787.492684197919
m_45_54_male : 1790.8477011595542
m_45_54_female : 1961.449065714448
m_55_64_male : 1559.587069259378
m_55_64_female : 1929.632490578886
m_65_more_male : 3151.255250566597
m_65_more_female : 4515.547524457055
```

```
47610 (young people neigborhood)

m_0_24_male : 952.999301566516
m_0_24_female : 857.9995121340911
m_25_34_male : 336.000093088714
m_25_34_female : 397.00021606163
m_35_44_male : 952.9993806331411
m_35_44_female : 897.9992779127381
m_45_54_male : 516.000023475282
m_45_54_female : 387.000339100203
m_55_64_male : 228.00025615555802
m_55_64_female : 213.0003394075266
m_65_more_male : 178.00100911120137
m_65_more_female : 207.00200334373375
```

Checking the data it agrees with what I see in those neighborhoods.

I want to point out that we have two massive ranges 0-24/65+ that win all the time. I think having ranges with 5 and 8 measurements for those categories is going to return an unbalanced result if you compare against 2 measurements. 

For example in the example cases above we can see that `m_35_44_male` is winning but for a tiny fraction of decimal. Why? because we are adding up from toddlers to adults in the 0-24 range.
